apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: wasm-clusters
  namespace: knawd
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      runtime: knawd